resourcedir = '../resources/'

title = "d.o.it"
description = "d.o.it - let's try things out"
copyright = "Copyright © d.o.it"
paginate = 9
enableGitInfo = true

# additional settings
baseURL = "https://d-oit.github.io/"
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true


[[module.imports]]
  path = 'github.com/gethinode/hinode'


