resourcedir = '../resources/'

title = "d.o.it"
description = "d.o.it - let's try things out"
copyright = "Copyright © d.o.it"
enableGitInfo = true

# additional settings
baseURL = "https://d-oit.github.io/"

canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 20

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

timeout = "180s"

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[outputFormats.REDIR]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

[mediaTypes."text/netlify"]
delimiter = ""

[outputs]
home = ["HTML", "RSS", "REDIR"]

[build]
  writeStats = true

[outputFormats]
  [outputFormats.XML]
    isPlainText = false
    mediaType = "application/xml"
    isHtml = false
    noUgly = true
    permalinkable = false
    name = "xml"

[minify]
  [minify.tdewolff.js]
    keepVarNames = true
    precision = 0
    version = 2022
  [minify.tdewolff.html]
    keepWhitespace = true

[[module.imports]]
  path = 'github.com/gethinode/hinode'
  localize = true