resourcedir = '../resources/'

title = "d.o.it"
description = "d.o.it - let's try things out"
copyright = "Copyright © d.o.it"
paginate = 9
enableGitInfo = true
timeout = "45s"

# additional settings
baseURL = "https://d-oit.github.io/"
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true

[[module.imports]]
  path = 'github.com/gethinode/hinode'

<<<<<<< HEAD
[[module.imports]]
  path = "github.com/privatemaker/headless-cms"

[outputs]
  home = [ "HTML", "RSS", "HeadlessCMSConfig" ]


=======
>>>>>>> daf74ef883baa6175cc9da4a690284d3da429ba4
