resourcedir = '../resources/'

title = "d.o.it"
description = "d.o.it - let's try things out"
copyright = "Copyright © d.o.it"
enableGitInfo = true

# additional settings
baseURL = "https://d-oit.github.io/"

canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 20

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

timeout = "180s"

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[outputFormats]
  [outputFormats.netlify]
    mediaType = "application/toml"
    baseName = "netlify"
    isPlainText = true
    notAlternative = true
    permalinkable = true
    root = true
  [outputFormats.server]
    mediaType = "application/toml"
    baseName = "server"
    isPlainText = true
    notAlternative = true
    permalinkable = true
    root = true
  [outputFormats.XML]
    isPlainText = false
    mediaType = "application/xml"
    isHtml = false
    noUgly = true
    permalinkable = false
    name = "xml"
  [outputFormats.REDIR]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true

[mediaTypes."text/netlify"]
delimiter = ""

[outputs]
home = ["HTML", "RSS", "REDIR", "netlify", "server"]

[build]
  writeStats = true
  
[taxonomies]
  tag = 'tags'

[pagination]
  pagerSize = 9

[minify]
  [minify.tdewolff.js]
    keepVarNames = true
    precision = 0
    version = 2022
  [minify.tdewolff.html]
    keepWhitespace = true

[segments]
  [segments.headers]
    [[segments.headers.includes]]
       kind = '{home}'
       output = '{netlify,server}'

[[module.imports]]
  path = 'github.com/gethinode/hinode'
