[main]
    separator = "-"
    description = "d.o.it - let's try things out"
    enableLanguageSelectionStorage = false 
    enableDarkMode = true
    modes = ["light", "dark"]
    showBackToTop = true
    showFooterPrivacy = true
    privacyPolicyURL = "privacy"

    loading = "lazy"
    breakpoint = "md"

[main.internalLinks]
    validate = true

[main.externalLinks]
    cue = true
    tab = true

[author]
    email = "d-oit@t-online.de"
    name = "d.o.it - Dominik Oswald"

[thumbnails]
    ratio = "21x9"

[home]
    sections = ["blog", "projects"]
    fullCover = false
    centerHeadline = false
    style = ""
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 6
        align = "start"

[navigation]
    anchor = true
    logo = "/img/logo/doitLogo.svg"
    color = "body"
    fixed = true
    overlay = false
    overlayMode = "dark"
    horizontal = false
    offset = "5.1rem"
    offsetXS = "5.1rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = false
    size = "md"

[messages]
    placement = "bottom-right"
 

[sharing]
    enabled = false
    sort = "weight"
    reverse = false
  

[sections]
    [sections.blog]
    title = "Blog"
        sort = "date"
        reverse = true
        cols = 2
        color = ""
        padding = "2"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-1 card-zoom card-body-margin card-emphasize"
        homepage = 2
        separator = true
   [sections.projects]
        title = "Projects"
        layout = "card"
        sort = "date"
        reverse = true
        nested = true
        cols = 2
        background = "body-tertiary"
        color = "body"
        padding = "3"
        header = "none"
        footer = "tags"
        orientation = "horizontal"
        style = "border-1 card-emphasize"
        homepage = 2
        separator = true
        wrap = true

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

# toml-docs-start theme-colors
[style]
    primary = "#d43900"
    secondary = "#ff6f61"
    success = "#28a745"
    info = "#17a2b8"
    warning = "#ffcc00"
    danger = "#e83e8c"
    light = "#f8f9fa"
    dark = "#343a40"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    themeFontPreload = "/fonts/inter-v12-latin-regular.woff2"
    purge = false # TODO: fix purge setting of example site
# toml-docs-end theme-colors

[schema]
    type = "Organization"
    name = "d.o.it"
    locale = "en-US"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = "https://www.linkedin.com/in/d-oit"
    github = "https://github.com/d-oit"
    bluesky = "https://bsky.app/profile/d-oit.bsky.social"
    section = "blog"
    [schema.author]
        name = "Dominik Oswald"
        # twitter = "https://twitter.com/markdumay"
        linkedin = "https://www.linkedin.com/in/d-oit"
        github = "https://github.com/d-oit"
        bluesky = "https://bsky.app/profile/d-oit.bsky.social"
   
