# toml-docs-start netlify
[build]
   publish = "public"
   command = "hugo --gc --minify"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from   = "/npmjs/*"
  to     = "/npmjs/"
  status = 200
# toml-docs-end netlify

[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"
        Content-Security-Policy = """\
            default-src 'self'; \
            child-src 'self' app.netlify.com; \
            script-src 'self' \
                https://*.netlify.app app.netlify.com netlify-cdp-loader.netlify.app \
                https://*.google-analytics.com https://*.googletagmanager.com; \
            style-src 'self' \
                https://*.netlify.app https://fonts.googleapis.com https://www.youtube.com; \
            object-src 'none'; \
            base-uri 'self'; \
            connect-src 'self'
                https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com; \
            font-src 'self' https://*.netlify.app https://fonts.gstatic.com; \
            frame-src 'self' https://www.youtube-nocookie.com https://www.youtube.com \
                app.netlify.com; \
            img-src 'self' data: https://*.imgix.net https://*.imagekit.io https://*.cloudinary.com https://*.netlify.app https://i.vimeocdn.com https://i.ytimg.com https://*.google-analytics.com https://*.googletagmanager.com https://tile.openstreetmap.org; \
            manifest-src 'self'; \
            media-src 'self' \
            """
        X-Frame-Options = "SAMEORIGIN"
        Referrer-Policy = "strict-origin"
        Permissions-Policy = """\
            geolocation=(), \
            midi=(), \
            sync-xhr=(), \
            microphone=(), \
            camera=(), \
            magnetometer=(), \
            gyroscope=(), \
            fullscreen=(), \
            payment=() \
            """
        cache-control = """\
            max-age=0, \
            no-cache, \
            no-store, \
            must-revalidate \
            """
        Access-Control-Allow-Origin = "*"


# toml-docs-end plugins
