[[main]]
  name = "Über"
  pageRef = "/about/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "/tags/"
  weight = 30

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://www.linkedin.com/in/d-oit"
  weight = 20

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/d-oit"
  weight = 10

[[social]]
  name = "Bluesky"
  pre = "fab fa-bluesky"
  url = "https://bsky.app/profile/d-oit.bsky.social"
  weight = 30  