name: Update Google Calendar Basket Calendar as JSON

on:
  schedule:
     - cron: '12 * * * *'  # Runs every 12 hour
  push:
    branches:
      - main

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ics pytz 


    - name: Run script
      run: |
        python update_basket_calendar_json.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add assets/json/free_basket_calendar.json
        git commit -m 'Update Google free basket Calendar JSON'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
